### ISSUE TITLE
No addresses are found with an uppercase/uppercases letter in transaction collection generated by mongo sync script.

### ISSUE THREAD

**Issue by katesroad** [fsn-dev/fsn-go-sdk#1]
For exanple: This address **_0x47Bb222e76ff205677132Fba7c6CFCDdFB4128d2_** exists in block.fusionnetwork.io 

but you can't find transaction histories with it in transaction histories generated by mongosync script

**Comment by cross-chain** [comment]
address have 3 leggal forms: all small case, all upper case, and mixed case.

we use `all small case` uniformly when storing in database (ref. `eth.getTransaction`, all from/to addresses are small case).

solution 1:  you case turn your address to all small case and then do the qurey.
solution 2: use mongodb "regex" with option "i" to match your address ignoring case.

**Comment by katesroad** [comment]
> address have 3 leggal forms: all small case, all upper case, and mixed case.
> 
> we use `all small case` uniformly when storing in the database (ref. `eth.getTransaction`, all from/to addresses are the small case).
> 
> solution 1: you case turn your address to all small case and then do the query.
> solution 2: use MongoDB "regex" with the option "i" to match your address ignoring case.

got it.  These solutions are doable.
