### ISSUE TITLE
Synchronizing blockchain data into MongoDB with HTTP protocol on ubuntu 18.04 causes a segmentation fault.

### ISSUE THREAD

**Issue by katesroad** [fsn-dev/fsn-go-sdk#2]
This error replicates every time on my ubuntu 18.04 system when I synchronize blockchain data with HTTP protocol at 9000 port

**Comment by Justice442** [comment]
What do you want me to do?

**Comment by cross-chain** [comment]
https://github.com/fsn-dev/fsn-go-sdk/blob/master/mongosync/README.md

**Comment by cross-chain** [comment]
please give me more info:

1. what does the log print?
2. is 9000 port your  running `efsn` node's RPC port?

for the usage, please refer to
<https://github.com/fsn-dev/fsn-go-sdk/blob/master/mongosync/README.md>

**Comment by katesroad** [comment]
I start a fusion node by   bash [fsnNode.sh](https://github.com/FUSIONFoundation/efsn/tree/master/QuickNodeSetup).

I checked many times, the default setting starts at 9000 port with HTTP protocol.

In this manner, I met several problems.
1>. It says it can't find the IPC file
so I tried another way by synchronizing with HTTP protocol.

Then after the synchronization script runs about 1~3 mins, the terminal reports a bug with prints:

```

INFO[03-11|17:30:24] syncRange in process                     id=3 number=170100 percentage=1.366
INFO[03-11|17:30:24] syncRange in process                     id=6 number=423500 percentage=1.344
INFO[03-11|17:30:24] syncRange in process                     id=10 number=761500 percentage=1.471
INFO[03-11|17:30:24] syncRange in process                     id=19 number=1521700 percentage=1.404
INFO[03-11|17:30:24] syncRange in process                     id=2 number=85600 percentage=1.334
INFO[03-11|17:30:25] syncRange in process                     id=7 number=508000 percentage=1.376
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x6d4dde]

goroutine 226649 [running]:
github.com/FusionFoundation/fsn-go-sdk/efsn/tools.GetBlockReward(0xc0006965a0, 0xc00048f1a0, 0x3, 0x3, 0x7f447ffe32f0)
  /home/uername/node/fsn-go-sdk/efsn/tools/calc.go:33 +0x14e
github.com/FusionFoundation/fsn-go-sdk/mongosync/syncer.calcBlockReward(0xc0006965a0, 0xc00048f1a0, 0x3, 0x3, 0xc000c5a000)
  /home/username/node/fsn-go-sdk/mongosync/syncer/parse.go:133 +0x131
github.com/FusionFoundation/fsn-go-sdk/mongosync/syncer.(*Worker).parseBlock(0xc0000acae0, 0xc0006965a0, 0xc00048f1a0, 0x3, 0x3, 0xc0000aae00)
  /home/username/node/fsn-go-sdk/mongosync/syncer/parse.go:109 +0x4b0
created by github.com/FusionFoundation/fsn-go-sdk/mongosync/syncer.(*Worker).startParser
  /home/username/node/fsn-go-sdk/mongosync/syncer/parse.go:75 +0x126
```

**Comment by katesroad** [comment]
Plus, I tried [guide](https://github.com/FUSIONFoundation/efsn#how-to-run-a-gateway),  my ubuntu 18.04 system meets the same problems too.

**Comment by cross-chain** [comment]
IPC file is `~/fusion-node/data/efsn.ipc` (default path)
